apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cstor-python-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: openebs-sc-example