apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-myapp
spec:
  selector:
    matchLabels:
      app: python-myapp
  template:
    metadata:
      labels:
        app: python-myapp
    spec:
      containers:
      - name: python-myapp-container
        image: dunefro/hostpath:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /workspace/apps/
            name: hostpath-volume
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: hostpath-pvc
